// https://leetcode.com/problems/find-the-difference/description/?envType=daily-question&envId=2023-09-25

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

#include <iostream>
using namespace std;

class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int sum1 = 0;
        int sum2 = 0;

        for (int i = 0; i < s.length(); i++)
        {
            sum1 += (s[i]-'a');
        }

        for (int i = 0; i < t.length(); i++)
        {
            sum2 += (t[i]-'a');
        }

        return ('a' + sum2 - sum1);
    }
};